#include <QMultiHash>

/* ------------------------
 * TEMPLATE FOR LANG DATA
 * -------------------------
 *
 * loadXXXData, where XXX is the language
 * keywords are the language keywords e.g, const
 * types are built-in types i.e, int, char, var
 * literals are words like, true false
 * builtin are the library functions
 * other can contain any other thing, for e.g, in cpp it contains the preprocessor

void loadXXXData(QMultiHash<QChar, QString> &types,
             QMultiHash<QChar, QString> &keywords,
             QMultiHash<QChar, QString> &builtin,
             QMultiHash<QChar, QString> &literals,
             QMultiHash<QChar, QString> &other){
    keywords = {
    };

    types = {
    };

    literals = {
    };

    builtin = {
    };

    other = {
    };
}

*/

void loadCppData(QMultiHash<QChar, QString> &types,
             QMultiHash<QChar, QString> &keywords,
             QMultiHash<QChar, QString> &builtin,
             QMultiHash<QChar, QString> &literals,
             QMultiHash<QChar, QString> &other){
    keywords = {
        {QLatin1Char('a'), QLatin1String("asm")},
        {QLatin1Char('a'), QLatin1String("auto")},
        {QLatin1Char('b'), QLatin1String("break")},
        {QLatin1Char('c'), QLatin1String("case")},
        {QLatin1Char('c'), QLatin1String("catch")},
        {QLatin1Char('c'), QLatin1String("const")},
        {QLatin1Char('c'), QLatin1String("const_cast")},
        {QLatin1Char('c'), QLatin1String("continue")},
        {QLatin1Char('d'), QLatin1String("default")},
        {QLatin1Char('d'), QLatin1String("delete")},
        {QLatin1Char('d'), QLatin1String("do")},
        {QLatin1Char('d'), QLatin1String("dynamic_cast")},
        {QLatin1Char('e'), QLatin1String("else")},
        {QLatin1Char('e'), QLatin1String("explicit")},
        {QLatin1Char('f'), QLatin1String("for")},
        {QLatin1Char('g'), QLatin1String("goto")},
        {QLatin1Char('i'), QLatin1String("if")},
        {QLatin1Char('m'), QLatin1String("mutable")},
        {QLatin1Char('n'), QLatin1String("namespace")},
        {QLatin1Char('n'), QLatin1String("new")},
        {QLatin1Char('o'), QLatin1String("operator")},
        {QLatin1Char('p'), QLatin1String("private")},
        {QLatin1Char('p'), QLatin1String("protected")},
        {QLatin1Char('p'), QLatin1String("public")},
        {QLatin1Char('r'), QLatin1String("register")},
        {QLatin1Char('r'), QLatin1String("reinterpret_cast")},
        {QLatin1Char('r'), QLatin1String("return")},
        {QLatin1Char('s'), QLatin1String("signal")},
        {QLatin1Char('s'), QLatin1String("signed")},
        {QLatin1Char('s'), QLatin1String("sizeof")},
        {QLatin1Char('s'), QLatin1String("slot")},
        {QLatin1Char('s'), QLatin1String("static")},
        {QLatin1Char('s'), QLatin1String("static_cast")},
        {QLatin1Char('s'), QLatin1String("switch")},
        {QLatin1Char('t'), QLatin1String("template")},
        {QLatin1Char('t'), QLatin1String("this")},
        {QLatin1Char('t'), QLatin1String("throw")},
        {QLatin1Char('t'), QLatin1String("try")},
        {QLatin1Char('t'), QLatin1String("typedef")},
        {QLatin1Char('u'), QLatin1String("unsigned")},
        {QLatin1Char('u'), QLatin1String("using")},
        {QLatin1Char('v'), QLatin1String("volatile")},
        {QLatin1Char('w'), QLatin1String("while")}
    };

    types = {
        {QLatin1Char('b'), QLatin1String("bool")},
        {QLatin1Char('c'), QLatin1String("char")},
        {QLatin1Char('c'), QLatin1String("class")},
        {QLatin1Char('d'), QLatin1String("double")},
        {QLatin1Char('e'), QLatin1String("enum")},
        {QLatin1Char('f'), QLatin1String("float")},
        {QLatin1Char('i'), QLatin1String("int")},
        {QLatin1Char('l'), QLatin1String("long")},
        {QLatin1Char('Q'), QLatin1String("QHash")},
        {QLatin1Char('Q'), QLatin1String("QList")},
        {QLatin1Char('Q'), QLatin1String("QMap")},
        {QLatin1Char('Q'), QLatin1String("QString")},
        {QLatin1Char('Q'), QLatin1String("QVector")},
        {QLatin1Char('s'), QLatin1String("short")},
        {QLatin1Char('s'), QLatin1String("string")},
        {QLatin1Char('s'), QLatin1String("struct")},
        {QLatin1Char('u'), QLatin1String("union")},
        {QLatin1Char('v'), QLatin1String("vector")},
        {QLatin1Char('v'), QLatin1String("void")},
        {QLatin1Char('w'), QLatin1String("wchar_t")},
    };

    literals = {
        {QLatin1Char('f'), QLatin1String("false")},
        {QLatin1Char('n'), QLatin1String("nullptr")},
        {QLatin1Char('N'), QLatin1String("NULL")},
        {QLatin1Char('t'), QLatin1String("true")}
    };

    builtin = {
        {QLatin1Char('s'), QLatin1String("std")},
        {QLatin1Char('s'), QLatin1String("string")},
        {QLatin1Char('w'), QLatin1String("wstring")},
        {QLatin1Char('c'), QLatin1String("cin")},
        {QLatin1Char('c'), QLatin1String("cout")},
        {QLatin1Char('c'), QLatin1String("cerr")},
        {QLatin1Char('c'), QLatin1String("clog")},
        {QLatin1Char('s'), QLatin1String("stdin")},
        {QLatin1Char('s'), QLatin1String("stdout")},
        {QLatin1Char('s'), QLatin1String("stderr")},
        {QLatin1Char('s'), QLatin1String("stringstream")},
        {QLatin1Char('i'), QLatin1String("istringstream")},
        {QLatin1Char('o'), QLatin1String("ostringstream")},
        {QLatin1Char('a'), QLatin1String("auto_ptr")},
        {QLatin1Char('d'), QLatin1String("deque")},
        {QLatin1Char('l'), QLatin1String("list")},
        {QLatin1Char('q'), QLatin1String("queue")},
        {QLatin1Char('s'), QLatin1String("stack")},
        {QLatin1Char('v'), QLatin1String("vector")},
        {QLatin1Char('m'), QLatin1String("map")},
        {QLatin1Char('s'), QLatin1String("set")},
        {QLatin1Char('b'), QLatin1String("bitset")},
        {QLatin1Char('m'), QLatin1String("multiset")},
        {QLatin1Char('m'), QLatin1String("multimap")},
        {QLatin1Char('u'), QLatin1String("unordered_set")},
        {QLatin1Char('u'), QLatin1String("unordered_map")},
        {QLatin1Char('u'), QLatin1String("unordered_multiset")},
        {QLatin1Char('u'), QLatin1String("unordered_multimap")},
        {QLatin1Char('a'), QLatin1String("array")},
        {QLatin1Char('s'), QLatin1String("shared_ptr")},
        {QLatin1Char('a'), QLatin1String("abort")},
        {QLatin1Char('t'), QLatin1String("terminate")},
        {QLatin1Char('a'), QLatin1String("abs")},
        {QLatin1Char('a'), QLatin1String("acos")},
        {QLatin1Char('a'), QLatin1String("asin")},
        {QLatin1Char('a'), QLatin1String("atan2")},
        {QLatin1Char('a'), QLatin1String("atan")},
        {QLatin1Char('c'), QLatin1String("calloc")},
        {QLatin1Char('c'), QLatin1String("ceil")},
        {QLatin1Char('c'), QLatin1String("cosh")},
        {QLatin1Char('c'), QLatin1String("cos")},
        {QLatin1Char('e'), QLatin1String("exit")},
        {QLatin1Char('e'), QLatin1String("exp")},
        {QLatin1Char('f'), QLatin1String("fabs")},
        {QLatin1Char('f'), QLatin1String("floor")},
        {QLatin1Char('f'), QLatin1String("fmod")},
        {QLatin1Char('f'), QLatin1String("fprintf")},
        {QLatin1Char('f'), QLatin1String("fputs")},
        {QLatin1Char('f'), QLatin1String("free")},
        {QLatin1Char('f'), QLatin1String("frexp")},
        {QLatin1Char('f'), QLatin1String("fscanf")},
        {QLatin1Char('f'), QLatin1String("future")},
        {QLatin1Char('i'), QLatin1String("isalnum")},
        {QLatin1Char('i'), QLatin1String("isalpha")},
        {QLatin1Char('i'), QLatin1String("iscntrl")},
        {QLatin1Char('i'), QLatin1String("isdigit")},
        {QLatin1Char('i'), QLatin1String("isgraph")},
        {QLatin1Char('i'), QLatin1String("islower")},
        {QLatin1Char('i'), QLatin1String("isprint")},
        {QLatin1Char('i'), QLatin1String("ispunct")},
        {QLatin1Char('i'), QLatin1String("isspace")},
        {QLatin1Char('i'), QLatin1String("isupper")},
        {QLatin1Char('i'), QLatin1String("isxdigit")},
        {QLatin1Char('t'), QLatin1String("tolower")},
        {QLatin1Char('t'), QLatin1String("toupper")},
        {QLatin1Char('l'), QLatin1String("labs")},
        {QLatin1Char('l'), QLatin1String("ldexp")},
        {QLatin1Char('l'), QLatin1String("log10")},
        {QLatin1Char('l'), QLatin1String("log")},
        {QLatin1Char('m'), QLatin1String("malloc")},
        {QLatin1Char('r'), QLatin1String("realloc")},
        {QLatin1Char('m'), QLatin1String("main")},
        {QLatin1Char('m'), QLatin1String("memchr")},
        {QLatin1Char('m'), QLatin1String("memcmp")},
        {QLatin1Char('m'), QLatin1String("memcpy")},
        {QLatin1Char('m'), QLatin1String("memset")},
        {QLatin1Char('m'), QLatin1String("modf")},
        {QLatin1Char('p'), QLatin1String("pow")},
        {QLatin1Char('p'), QLatin1String("printf")},
        {QLatin1Char('p'), QLatin1String("putchar")},
        {QLatin1Char('p'), QLatin1String("puts")},
        {QLatin1Char('s'), QLatin1String("scanf")},
        {QLatin1Char('s'), QLatin1String("sinh")},
        {QLatin1Char('s'), QLatin1String("sin")},
        {QLatin1Char('s'), QLatin1String("snprintf")},
        {QLatin1Char('s'), QLatin1String("sprintf")},
        {QLatin1Char('s'), QLatin1String("sqrt")},
        {QLatin1Char('s'), QLatin1String("sscanf")},
        {QLatin1Char('s'), QLatin1String("strcat")},
        {QLatin1Char('s'), QLatin1String("strchr")},
        {QLatin1Char('s'), QLatin1String("strcmp")},
        {QLatin1Char('s'), QLatin1String("strcpy")},
        {QLatin1Char('s'), QLatin1String("strcspn")},
        {QLatin1Char('s'), QLatin1String("strlen")},
        {QLatin1Char('s'), QLatin1String("strncat")},
        {QLatin1Char('s'), QLatin1String("strncmp")},
        {QLatin1Char('s'), QLatin1String("strncpy")},
        {QLatin1Char('s'), QLatin1String("strpbrk")},
        {QLatin1Char('s'), QLatin1String("strrchr")},
        {QLatin1Char('s'), QLatin1String("strspn")},
        {QLatin1Char('s'), QLatin1String("strstr")},
        {QLatin1Char('t'), QLatin1String("tanh")},
        {QLatin1Char('t'), QLatin1String("tan")},
        {QLatin1Char('v'), QLatin1String("vfprintf")},
        {QLatin1Char('v'), QLatin1String("vprintf")},
        {QLatin1Char('v'), QLatin1String("vsprintf")},
        {QLatin1Char('e'), QLatin1String("endl")},
        {QLatin1Char('i'), QLatin1String("initializer_list")},
        {QLatin1Char('u'), QLatin1String("unique_ptr")},
        {QLatin1Char('c'), QLatin1String("complex")},
        {QLatin1Char('i'), QLatin1String("imaginary")}
    };

    other = {
        {QLatin1Char('d'), QLatin1String("define")},
        {QLatin1Char('e'), QLatin1String("else")},
        {QLatin1Char('e'), QLatin1String("elif")},
        {QLatin1Char('e'), QLatin1String("endif")},
        {QLatin1Char('e'), QLatin1String("error")},
        {QLatin1Char('i'), QLatin1String("if")},
        {QLatin1Char('i'), QLatin1String("ifdef")},
        {QLatin1Char('i'), QLatin1String("ifndef")},
        {QLatin1Char('i'), QLatin1String("include")},
        {QLatin1Char('l'), QLatin1String("line")},
        {QLatin1Char('p'), QLatin1String("pragma")},
        {QLatin1Char('P'), QLatin1String("_Pragma")},
        {QLatin1Char('u'), QLatin1String("undef")},
        {QLatin1Char('w'), QLatin1String("warning")}
    };
}

void loadShellData(QMultiHash<QChar, QString> &types,
             QMultiHash<QChar, QString> &keywords,
             QMultiHash<QChar, QString> &builtin,
             QMultiHash<QChar, QString> &literals,
             QMultiHash<QChar, QString> &other){
    keywords = {
        {QLatin1Char('i'), QLatin1String("if")},
        {QLatin1Char('t'), QLatin1String("then")},
        {QLatin1Char('e'), QLatin1String("else")},
        {QLatin1Char('e'), QLatin1String("elif")},
        {QLatin1Char('f'), QLatin1String("fi")},
        {QLatin1Char('f'), QLatin1String("for")},
        {QLatin1Char('w'), QLatin1String("while")},
        {QLatin1Char('i'), QLatin1String("in")},
        {QLatin1Char('d'), QLatin1String("do")},
        {QLatin1Char('d'), QLatin1String("done")},
        {QLatin1Char('c'), QLatin1String("case")},
        {QLatin1Char('e'), QLatin1String("esac")},
        {QLatin1Char('f'), QLatin1String("function")}
    };

    types = {
    };

    literals = {
        {QLatin1Char('f'), QLatin1String("false")},
        {QLatin1Char('t'), QLatin1String("true")}
    };

    builtin = {
        {QLatin1Char('b'), QLatin1String("break")},
        {QLatin1Char('c'), QLatin1String("cd")},
        {QLatin1Char('c'), QLatin1String("continue")},
        {QLatin1Char('e'), QLatin1String("eval")},
        {QLatin1Char('e'), QLatin1String("exec")},
        {QLatin1Char('e'), QLatin1String("exit")},
        {QLatin1Char('e'), QLatin1String("export")},
        {QLatin1Char('g'), QLatin1String("getopts")},
        {QLatin1Char('h'), QLatin1String("hash")},
        {QLatin1Char('p'), QLatin1String("pwd")},
        {QLatin1Char('r'), QLatin1String("readonly")},
        {QLatin1Char('r'), QLatin1String("return")},
        {QLatin1Char('s'), QLatin1String("shift")},
        {QLatin1Char('t'), QLatin1String("test")},
        {QLatin1Char('t'), QLatin1String("timestrap")},
        {QLatin1Char('u'), QLatin1String("umask")},
        {QLatin1Char('u'), QLatin1String("unset")},
        {QLatin1Char('B'), QLatin1String("Bash")},
        {QLatin1Char('a'), QLatin1String("alias")},
        {QLatin1Char('b'), QLatin1String("bind")},
        {QLatin1Char('b'), QLatin1String("builtin")},
        {QLatin1Char('c'), QLatin1String("caller")},
        {QLatin1Char('c'), QLatin1String("command")},
        {QLatin1Char('d'), QLatin1String("declare")},
        {QLatin1Char('e'), QLatin1String("echo")},
        {QLatin1Char('e'), QLatin1String("enable")},
        {QLatin1Char('h'), QLatin1String("help")},
        {QLatin1Char('l'), QLatin1String("let")},
        {QLatin1Char('l'), QLatin1String("local")},
        {QLatin1Char('l'), QLatin1String("logout")},
        {QLatin1Char('m'), QLatin1String("mapfile")},
        {QLatin1Char('p'), QLatin1String("printfread")},
        {QLatin1Char('r'), QLatin1String("readarray")},
        {QLatin1Char('s'), QLatin1String("source")},
        {QLatin1Char('t'), QLatin1String("type")},
        {QLatin1Char('t'), QLatin1String("typeset")},
        {QLatin1Char('u'), QLatin1String("ulimit")},
        {QLatin1Char('u'), QLatin1String("unalias")},
        {QLatin1Char('m'), QLatin1String("modifiers")},
        {QLatin1Char('s'), QLatin1String("set")},
        {QLatin1Char('s'), QLatin1String("shopt")},
        {QLatin1Char('a'), QLatin1String("autoload")},
        {QLatin1Char('b'), QLatin1String("bg")},
        {QLatin1Char('b'), QLatin1String("bindkey")},
        {QLatin1Char('b'), QLatin1String("bye")},
        {QLatin1Char('c'), QLatin1String("cap")},
        {QLatin1Char('c'), QLatin1String("chdir")},
        {QLatin1Char('c'), QLatin1String("clone")},
        {QLatin1Char('c'), QLatin1String("comparguments")},
        {QLatin1Char('c'), QLatin1String("compcall")},
        {QLatin1Char('c'), QLatin1String("compctl")},
        {QLatin1Char('c'), QLatin1String("compdescribe")},
        {QLatin1Char('c'), QLatin1String("compfilescompgroups")},
        {QLatin1Char('c'), QLatin1String("compquote")},
        {QLatin1Char('c'), QLatin1String("comptags")},
        {QLatin1Char('c'), QLatin1String("comptry")},
        {QLatin1Char('c'), QLatin1String("compvalues")},
        {QLatin1Char('d'), QLatin1String("dirs")},
        {QLatin1Char('d'), QLatin1String("disable")},
        {QLatin1Char('d'), QLatin1String("disown")},
        {QLatin1Char('e'), QLatin1String("echotc")},
        {QLatin1Char('e'), QLatin1String("echoti")},
        {QLatin1Char('e'), QLatin1String("emulatefc")},
        {QLatin1Char('f'), QLatin1String("fg")},
        {QLatin1Char('f'), QLatin1String("float")},
        {QLatin1Char('f'), QLatin1String("functions")},
        {QLatin1Char('g'), QLatin1String("getcap")},
        {QLatin1Char('g'), QLatin1String("getln")},
        {QLatin1Char('h'), QLatin1String("history")},
        {QLatin1Char('i'), QLatin1String("integer")},
        {QLatin1Char('j'), QLatin1String("jobs")},
        {QLatin1Char('k'), QLatin1String("kill")},
        {QLatin1Char('l'), QLatin1String("limit")},
        {QLatin1Char('l'), QLatin1String("log")},
        {QLatin1Char('n'), QLatin1String("noglob")},
        {QLatin1Char('p'), QLatin1String("popd")},
        {QLatin1Char('p'), QLatin1String("printpushd")},
        {QLatin1Char('p'), QLatin1String("pushln")},
        {QLatin1Char('r'), QLatin1String("rehash")},
        {QLatin1Char('s'), QLatin1String("sched")},
        {QLatin1Char('s'), QLatin1String("setcap")},
        {QLatin1Char('s'), QLatin1String("setopt")},
        {QLatin1Char('s'), QLatin1String("stat")},
        {QLatin1Char('s'), QLatin1String("suspend")},
        {QLatin1Char('t'), QLatin1String("ttyctl")},
        {QLatin1Char('u'), QLatin1String("unfunction")},
        {QLatin1Char('u'), QLatin1String("unhash")},
        {QLatin1Char('u'), QLatin1String("unlimitunsetopt")},
        {QLatin1Char('v'), QLatin1String("vared")},
        {QLatin1Char('w'), QLatin1String("wait")},
        {QLatin1Char('w'), QLatin1String("whence")},
        {QLatin1Char('w'), QLatin1String("where")},
        {QLatin1Char('w'), QLatin1String("which")},
        {QLatin1Char('z'), QLatin1String("zcompile")},
        {QLatin1Char('z'), QLatin1String("zformat")},
        {QLatin1Char('z'), QLatin1String("zftp")},
        {QLatin1Char('z'), QLatin1String("zle")},
        {QLatin1Char('z'), QLatin1String("zmodload")},
        {QLatin1Char('z'), QLatin1String("zparseopts")},
        {QLatin1Char('z'), QLatin1String("zprof")},
        {QLatin1Char('z'), QLatin1String("zpty")},
        {QLatin1Char('z'), QLatin1String("zregexparse")},
        {QLatin1Char('z'), QLatin1String("zsocket")},
        {QLatin1Char('z'), QLatin1String("zstyle")},
        {QLatin1Char('z'), QLatin1String("ztcp")}
    };

    other = {
    };
}

void loadJSData(QMultiHash<QChar, QString> &types,
             QMultiHash<QChar, QString> &keywords,
             QMultiHash<QChar, QString> &builtin,
             QMultiHash<QChar, QString> &literals,
             QMultiHash<QChar, QString> &other){
    keywords = {
        {QLatin1Char('i'), QLatin1String("in")},
        {QLatin1Char('o'), QLatin1String("of")},
        {QLatin1Char('i'), QLatin1String("if")},
        {QLatin1Char('f'), QLatin1String("for")},
        {QLatin1Char('w'), QLatin1String("while")},
        {QLatin1Char('f'), QLatin1String("finally")},
        {QLatin1Char('n'), QLatin1String("new")},
        {QLatin1Char('f'), QLatin1String("function")},
        {QLatin1Char('d'), QLatin1String("do")},
        {QLatin1Char('r'), QLatin1String("return")},
        {QLatin1Char('v'), QLatin1String("void")},
        {QLatin1Char('e'), QLatin1String("else")},
        {QLatin1Char('b'), QLatin1String("break")},
        {QLatin1Char('c'), QLatin1String("catch")},
        {QLatin1Char('i'), QLatin1String("instanceof")},
        {QLatin1Char('w'), QLatin1String("with")},
        {QLatin1Char('t'), QLatin1String("throw")},
        {QLatin1Char('c'), QLatin1String("case")},
        {QLatin1Char('d'), QLatin1String("default")},
        {QLatin1Char('t'), QLatin1String("try")},
        {QLatin1Char('t'), QLatin1String("this")},
        {QLatin1Char('s'), QLatin1String("switch")},
        {QLatin1Char('c'), QLatin1String("continue")},
        {QLatin1Char('t'), QLatin1String("typeof")},
        {QLatin1Char('d'), QLatin1String("delete")},
        {QLatin1Char('l'), QLatin1String("let")},
        {QLatin1Char('y'), QLatin1String("yield")},
        {QLatin1Char('c'), QLatin1String("const")},
        {QLatin1Char('e'), QLatin1String("export")},
        {QLatin1Char('s'), QLatin1String("super")},
        {QLatin1Char('d'), QLatin1String("debugger")},
        {QLatin1Char('a'), QLatin1String("as")},
        {QLatin1Char('a'), QLatin1String("async")},
        {QLatin1Char('a'), QLatin1String("await")},
        {QLatin1Char('s'), QLatin1String("static")},
        {QLatin1Char('i'), QLatin1String("import")},
        {QLatin1Char('f'), QLatin1String("from")},
        {QLatin1Char('a'), QLatin1String("as")}
    };

    types = {
        {QLatin1Char('v'), QLatin1String("var")},
        {QLatin1Char('c'), QLatin1String("class")},
        {QLatin1Char('b'), QLatin1String("byte")},
        {QLatin1Char('e'), QLatin1String("enum")},
        {QLatin1Char('f'), QLatin1String("float")},
        {QLatin1Char('s'), QLatin1String("short")},
        {QLatin1Char('l'), QLatin1String("long")},
        {QLatin1Char('i'), QLatin1String("int")},
        {QLatin1Char('v'), QLatin1String("void")},
        {QLatin1Char('b'), QLatin1String("boolean")},
        {QLatin1Char('d'), QLatin1String("double")}
    };

    literals = {
        {QLatin1Char('f'), QLatin1String("false")},
        {QLatin1Char('n'), QLatin1String("null")},
        {QLatin1Char('t'), QLatin1String("true")},
        {QLatin1Char('u'), QLatin1String("undefined")},
        {QLatin1Char('N'), QLatin1String("NaN")},
        {QLatin1Char('I'), QLatin1String("Infinity")}
    };

    builtin = {
        {QLatin1Char('e'), QLatin1String("eval")},
        {QLatin1Char('i'), QLatin1String("isFinite")},
        {QLatin1Char('i'), QLatin1String("isNaN")},
        {QLatin1Char('p'), QLatin1String("parseFloat")},
        {QLatin1Char('p'), QLatin1String("parseInt")},
        {QLatin1Char('d'), QLatin1String("decodeURI")},
        {QLatin1Char('d'), QLatin1String("decodeURIComponent")},
        {QLatin1Char('e'), QLatin1String("encodeURI")},
        {QLatin1Char('e'), QLatin1String("encodeURIComponent")},
        {QLatin1Char('e'), QLatin1String("escape")},
        {QLatin1Char('u'), QLatin1String("unescape")},
        {QLatin1Char('O'), QLatin1String("Object")},
        {QLatin1Char('F'), QLatin1String("Function")},
        {QLatin1Char('B'), QLatin1String("Boolean")},
        {QLatin1Char('E'), QLatin1String("Error")},
        {QLatin1Char('E'), QLatin1String("EvalError")},
        {QLatin1Char('I'), QLatin1String("InternalError")},
        {QLatin1Char('R'), QLatin1String("RangeError")},
        {QLatin1Char('R'), QLatin1String("ReferenceError")},
        {QLatin1Char('S'), QLatin1String("StopIteration")},
        {QLatin1Char('S'), QLatin1String("SyntaxError")},
        {QLatin1Char('T'), QLatin1String("TypeError")},
        {QLatin1Char('U'), QLatin1String("URIError")},
        {QLatin1Char('N'), QLatin1String("Number")},
        {QLatin1Char('M'), QLatin1String("Math")},
        {QLatin1Char('D'), QLatin1String("Date")},
        {QLatin1Char('S'), QLatin1String("String")},
        {QLatin1Char('R'), QLatin1String("RegExp")},
        {QLatin1Char('A'), QLatin1String("Array")},
        {QLatin1Char('F'), QLatin1String("Float32Array")},
        {QLatin1Char('F'), QLatin1String("Float64Array")},
        {QLatin1Char('I'), QLatin1String("Int16Array")},
        {QLatin1Char('I'), QLatin1String("Int32Array")},
        {QLatin1Char('I'), QLatin1String("Int8Array")},
        {QLatin1Char('U'), QLatin1String("Uint16Array")},
        {QLatin1Char('U'), QLatin1String("Uint32Array")},
        {QLatin1Char('U'), QLatin1String("Uint8Array")},
        {QLatin1Char('U'), QLatin1String("Uint8ClampedArray")},
        {QLatin1Char('A'), QLatin1String("ArrayBuffer")},
        {QLatin1Char('D'), QLatin1String("DataView")},
        {QLatin1Char('J'), QLatin1String("JSON")},
        {QLatin1Char('I'), QLatin1String("Intl")},
        {QLatin1Char('a'), QLatin1String("arguments")},
        {QLatin1Char('r'), QLatin1String("require")},
        {QLatin1Char('m'), QLatin1String("module")},
        {QLatin1Char('c'), QLatin1String("console")},
        {QLatin1Char('w'), QLatin1String("window")},
        {QLatin1Char('d'), QLatin1String("document")},
        {QLatin1Char('S'), QLatin1String("Symbol")},
        {QLatin1Char('S'), QLatin1String("Set")},
        {QLatin1Char('M'), QLatin1String("Map")},
        {QLatin1Char('W'), QLatin1String("WeakSet")},
        {QLatin1Char('W'), QLatin1String("WeakMap")},
        {QLatin1Char('P'), QLatin1String("Proxy")},
        {QLatin1Char('R'), QLatin1String("Reflect")},
        {QLatin1Char('P'), QLatin1String("Promise")}
    };

    other = {
    };

}

void loadPHPData(QMultiHash<QChar, QString> &types,
             QMultiHash<QChar, QString> &keywords,
             QMultiHash<QChar, QString> &builtin,
             QMultiHash<QChar, QString> &literals,
             QMultiHash<QChar, QString> &other){
    keywords = {
        {QLatin1Char('a'), QLatin1String("and")},
        {QLatin1Char('l'), QLatin1String("list")},
        {QLatin1Char('a'), QLatin1String("abstract")},
        {QLatin1Char('g'), QLatin1String("global")},
        {QLatin1Char('p'), QLatin1String("private")},
        {QLatin1Char('e'), QLatin1String("echo")},
        {QLatin1Char('i'), QLatin1String("interface")},
        {QLatin1Char('a'), QLatin1String("as")},
        {QLatin1Char('s'), QLatin1String("static")},
        {QLatin1Char('e'), QLatin1String("endswitch")},
        {QLatin1Char('i'), QLatin1String("if")},
        {QLatin1Char('e'), QLatin1String("endwhile")},
        {QLatin1Char('o'), QLatin1String("or")},
        {QLatin1Char('c'), QLatin1String("const")},
        {QLatin1Char('f'), QLatin1String("for")},
        {QLatin1Char('e'), QLatin1String("endforeach")},
        {QLatin1Char('s'), QLatin1String("self")},
        {QLatin1Char('w'), QLatin1String("while")},
        {QLatin1Char('i'), QLatin1String("isset")},
        {QLatin1Char('p'), QLatin1String("public")},
        {QLatin1Char('p'), QLatin1String("protected")},
        {QLatin1Char('e'), QLatin1String("exit")},
        {QLatin1Char('f'), QLatin1String("foreach")},
        {QLatin1Char('t'), QLatin1String("throw")},
        {QLatin1Char('e'), QLatin1String("elseif")},
        {QLatin1Char('e'), QLatin1String("empty")},
        {QLatin1Char('d'), QLatin1String("do")},
        {QLatin1Char('x'), QLatin1String("xor")},
        {QLatin1Char('r'), QLatin1String("return")},
        {QLatin1Char('p'), QLatin1String("parent")},
        {QLatin1Char('c'), QLatin1String("clone")},
        {QLatin1Char('u'), QLatin1String("use")},
        {QLatin1Char('e'), QLatin1String("else")},
        {QLatin1Char('b'), QLatin1String("break")},
        {QLatin1Char('p'), QLatin1String("print")},
        {QLatin1Char('e'), QLatin1String("eval")},
        {QLatin1Char('n'), QLatin1String("new")},
        {QLatin1Char('c'), QLatin1String("catch")},
        {QLatin1Char('c'), QLatin1String("case")},
        {QLatin1Char('e'), QLatin1String("exception")},
        {QLatin1Char('d'), QLatin1String("default")},
        {QLatin1Char('d'), QLatin1String("die")},
        {QLatin1Char('e'), QLatin1String("enddeclare")},
        {QLatin1Char('f'), QLatin1String("final")},
        {QLatin1Char('t'), QLatin1String("try")},
        {QLatin1Char('s'), QLatin1String("switch")},
        {QLatin1Char('c'), QLatin1String("continue")},
        {QLatin1Char('e'), QLatin1String("endfor")},
        {QLatin1Char('e'), QLatin1String("endif")},
        {QLatin1Char('d'), QLatin1String("declare")},
        {QLatin1Char('u'), QLatin1String("unset")},
        {QLatin1Char('t'), QLatin1String("trait")},
        {QLatin1Char('g'), QLatin1String("goto")},
        {QLatin1Char('i'), QLatin1String("instanceof")},
        {QLatin1Char('i'), QLatin1String("insteadof")},
        {QLatin1Char('y'), QLatin1String("yield")},
        {QLatin1Char('f'), QLatin1String("finally")}
    };

    types = {
        {QLatin1Char('v'), QLatin1String("var")},
        {QLatin1Char('c'), QLatin1String("class")},
        {QLatin1Char('e'), QLatin1String("enum")},
        {QLatin1Char('a'), QLatin1String("array")}
    };

    literals = {
        {QLatin1Char('f'), QLatin1String("false")},
        {QLatin1Char('t'), QLatin1String("true")},
        {QLatin1Char('n'), QLatin1String("null")}
    };

    builtin = {


    };

    other = {
        {QLatin1Char('i'), QLatin1String("include_once")},
        {QLatin1Char('i'), QLatin1String("include")},
        {QLatin1Char('_'), QLatin1String("__FILE__")},
        {QLatin1Char('r'), QLatin1String("require")},
        {QLatin1Char('r'), QLatin1String("require_once")},
        {QLatin1Char('_'), QLatin1String("__CLASS__")},
        {QLatin1Char('_'), QLatin1String("__LINE__")},
        {QLatin1Char('_'), QLatin1String("__METHOD__")},
        {QLatin1Char('_'), QLatin1String("__FUNCTION__")},
        {QLatin1Char('_'), QLatin1String("__DIR__")},
        {QLatin1Char('_'), QLatin1String("__NAMESPACE__")},

        {QLatin1Char('S'), QLatin1String("SERVER")},
        {QLatin1Char('G'), QLatin1String("GET")},
        {QLatin1Char('P'), QLatin1String("POST")},
        {QLatin1Char('F'), QLatin1String("FILES")},
        {QLatin1Char('R'), QLatin1String("REQUEST")},
        {QLatin1Char('S'), QLatin1String("SESSION")},
        {QLatin1Char('E'), QLatin1String("ENV")},
        {QLatin1Char('C'), QLatin1String("COOKIE")},
        {QLatin1Char('G'), QLatin1String("GLOBALS")},
        {QLatin1Char('H'), QLatin1String("HTTP_RAW_POST_DATA")},
        {QLatin1Char('a'), QLatin1String("argc")},
        {QLatin1Char('a'), QLatin1String("argv")},
        {QLatin1Char('p'), QLatin1String("php_errormsg")},
        {QLatin1Char('h'), QLatin1String("http_response_header")}
    };

}

void loadQMLData(QMultiHash<QChar, QString> &types,
             QMultiHash<QChar, QString> &keywords,
             QMultiHash<QChar, QString> &builtin,
             QMultiHash<QChar, QString> &literals,
             QMultiHash<QChar, QString> &other){
    keywords = {
        {QLatin1Char('d'), QLatin1String("default")},
        {QLatin1Char('p'), QLatin1String("property")},
        {QLatin1Char('i'), QLatin1String("int")},
        {QLatin1Char('v'), QLatin1String("var")},
        {QLatin1Char('s'), QLatin1String("string")},
        {QLatin1Char('f'), QLatin1String("function")},
        {QLatin1Char('r'), QLatin1String("readonly")},
        {QLatin1Char('M'), QLatin1String("MouseArea")},
        {QLatin1Char('d'), QLatin1String("delegate")},
        {QLatin1Char('i'), QLatin1String("if")},
        {QLatin1Char('e'), QLatin1String("else")},

        {QLatin1Char('e'), QLatin1String("eval")},
        {QLatin1Char('i'), QLatin1String("isFinite")},
        {QLatin1Char('i'), QLatin1String("isNaN")},
        {QLatin1Char('p'), QLatin1String("parseFloat")},
        {QLatin1Char('p'), QLatin1String("parseInt")},
        {QLatin1Char('d'), QLatin1String("decodeURI")},
        {QLatin1Char('d'), QLatin1String("decodeURIComponent")},
        {QLatin1Char('e'), QLatin1String("encodeURI")},
        {QLatin1Char('e'), QLatin1String("encodeURIComponent")},
        {QLatin1Char('e'), QLatin1String("escape")},
        {QLatin1Char('u'), QLatin1String("unescape")},
        {QLatin1Char('O'), QLatin1String("Object")},
        {QLatin1Char('E'), QLatin1String("Error")},
        {QLatin1Char('E'), QLatin1String("EvalError")},
        {QLatin1Char('I'), QLatin1String("InternalError")},
        {QLatin1Char('R'), QLatin1String("RangeError")},
        {QLatin1Char('R'), QLatin1String("ReferenceError")},
        {QLatin1Char('S'), QLatin1String("StopIteration")},
        {QLatin1Char('S'), QLatin1String("SyntaxError")},
        {QLatin1Char('T'), QLatin1String("TypeError")},
        {QLatin1Char('U'), QLatin1String("URIError")},
        {QLatin1Char('N'), QLatin1String("Number")},
        {QLatin1Char('M'), QLatin1String("Math")},
        {QLatin1Char('D'), QLatin1String("Date")},
        {QLatin1Char('S'), QLatin1String("String")},
        {QLatin1Char('R'), QLatin1String("RegExp")},
        {QLatin1Char('A'), QLatin1String("Array")},
        {QLatin1Char('F'), QLatin1String("Float32Array")},
        {QLatin1Char('F'), QLatin1String("Float64Array")},
        {QLatin1Char('I'), QLatin1String("Int16Array")},
        {QLatin1Char('I'), QLatin1String("Int32Array")},
        {QLatin1Char('I'), QLatin1String("Int8Array")},
        {QLatin1Char('U'), QLatin1String("Uint16Array")},
        {QLatin1Char('U'), QLatin1String("Uint32Array")},
        {QLatin1Char('U'), QLatin1String("Uint8Array")},
        {QLatin1Char('U'), QLatin1String("Uint8ClampedArray")},
        {QLatin1Char('A'), QLatin1String("ArrayBuffer")},
        {QLatin1Char('D'), QLatin1String("DataView")},
        {QLatin1Char('J'), QLatin1String("JSON")},
        {QLatin1Char('I'), QLatin1String("Intl")},
        {QLatin1Char('a'), QLatin1String("arguments")},
        {QLatin1Char('m'), QLatin1String("module")},
        {QLatin1Char('c'), QLatin1String("console")},
        {QLatin1Char('w'), QLatin1String("window")},
        {QLatin1Char('d'), QLatin1String("document")},
        {QLatin1Char('S'), QLatin1String("Symbol")},
        {QLatin1Char('S'), QLatin1String("Set")},
        {QLatin1Char('M'), QLatin1String("Map")},
        {QLatin1Char('W'), QLatin1String("WeakSet")},
        {QLatin1Char('W'), QLatin1String("WeakMap")},
        {QLatin1Char('P'), QLatin1String("Proxy")},
        {QLatin1Char('R'), QLatin1String("Reflect")},
        {QLatin1Char('B'), QLatin1String("Behavior")},
        {QLatin1Char('c'), QLatin1String("color")},
        {QLatin1Char('c'), QLatin1String("coordinate")},
        {QLatin1Char('d'), QLatin1String("date")},
        {QLatin1Char('e'), QLatin1String("enumeration")},
        {QLatin1Char('f'), QLatin1String("font")},
        {QLatin1Char('g'), QLatin1String("geocircle")},
        {QLatin1Char('g'), QLatin1String("georectangle")},
        {QLatin1Char('g'), QLatin1String("geoshape")},
        {QLatin1Char('l'), QLatin1String("list")},
        {QLatin1Char('m'), QLatin1String("matrix4x4")},
        {QLatin1Char('p'), QLatin1String("parent")},
        {QLatin1Char('p'), QLatin1String("point")},
        {QLatin1Char('q'), QLatin1String("quaternion")},
        {QLatin1Char('r'), QLatin1String("real")},
        {QLatin1Char('s'), QLatin1String("size")},
        {QLatin1Char('s'), QLatin1String("string")},
        {QLatin1Char('v'), QLatin1String("variant")},
        {QLatin1Char('v'), QLatin1String("vector2d")},
        {QLatin1Char('v'), QLatin1String("vector3d")},
        {QLatin1Char('v'), QLatin1String("vector4d")},
        {QLatin1Char('P'), QLatin1String("Promise")}
    };

    types = {
        {QLatin1Char('R'), QLatin1String("Rectangle")},
        {QLatin1Char('T'), QLatin1String("Text")},
        {QLatin1Char('c'), QLatin1String("color")},
        {QLatin1Char('I'), QLatin1String("Item")},
        {QLatin1Char('u'), QLatin1String("url")},
        {QLatin1Char('C'), QLatin1String("Component")},
        {QLatin1Char('B'), QLatin1String("Button")},
        {QLatin1Char('T'), QLatin1String("TextInput")},
        {QLatin1Char('L'), QLatin1String("ListView")},


    };

    literals = {
        {QLatin1Char('f'), QLatin1String("false")},
        {QLatin1Char('t'), QLatin1String("true")}
    };

    builtin = {

    };

    other = {
        {QLatin1Char('i'), QLatin1String("import")}
    };

}

void loadPythonData(QMultiHash<QChar, QString> &types,
             QMultiHash<QChar, QString> &keywords,
             QMultiHash<QChar, QString> &builtin,
             QMultiHash<QChar, QString> &literals,
             QMultiHash<QChar, QString> &other){
    keywords = {
        {QLatin1Char('a'), QLatin1String("and")},
        {QLatin1Char('e'), QLatin1String("elif")},
        {QLatin1Char('i'), QLatin1String("is")},
        {QLatin1Char('g'), QLatin1String("global")},
        {QLatin1Char('a'), QLatin1String("as")},
        {QLatin1Char('i'), QLatin1String("in")},
        {QLatin1Char('i'), QLatin1String("if")},
        {QLatin1Char('f'), QLatin1String("from")},
        {QLatin1Char('r'), QLatin1String("raise")},
        {QLatin1Char('f'), QLatin1String("for")},
        {QLatin1Char('e'), QLatin1String("except")},
        {QLatin1Char('f'), QLatin1String("finally")},
        {QLatin1Char('p'), QLatin1String("print")},
        {QLatin1Char('p'), QLatin1String("pass")},
        {QLatin1Char('r'), QLatin1String("return")},
        {QLatin1Char('e'), QLatin1String("exec")},
        {QLatin1Char('e'), QLatin1String("else")},
        {QLatin1Char('b'), QLatin1String("break")},
        {QLatin1Char('n'), QLatin1String("not")},
        {QLatin1Char('w'), QLatin1String("with")},
        {QLatin1Char('c'), QLatin1String("class")},
        {QLatin1Char('a'), QLatin1String("assert")},
        {QLatin1Char('y'), QLatin1String("yield")},
        {QLatin1Char('t'), QLatin1String("try")},
        {QLatin1Char('w'), QLatin1String("while")},
        {QLatin1Char('c'), QLatin1String("continue")},
        {QLatin1Char('d'), QLatin1String("del")},
        {QLatin1Char('o'), QLatin1String("or")},
        {QLatin1Char('d'), QLatin1String("def")},
        {QLatin1Char('l'), QLatin1String("lambda")},
        {QLatin1Char('a'), QLatin1String("async")},
        {QLatin1Char('a'), QLatin1String("await")},
        {QLatin1Char('n'), QLatin1String("nonlocal")},
    };

    types = {

    };

    literals = {
        {QLatin1Char('F'), QLatin1String("False")},
        {QLatin1Char('T'), QLatin1String("True")},
        {QLatin1Char('N'), QLatin1String("None")}
    };

    builtin = {
        {QLatin1Char('_'), QLatin1String("__import__")},
        {QLatin1Char('a'), QLatin1String("abs")},
        {QLatin1Char('a'), QLatin1String("all")},
        {QLatin1Char('a'), QLatin1String("any")},
        {QLatin1Char('a'), QLatin1String("apply")},
        {QLatin1Char('a'), QLatin1String("ascii")},
        {QLatin1Char('b'), QLatin1String("basestring")},
        {QLatin1Char('b'), QLatin1String("bin")},
        {QLatin1Char('b'), QLatin1String("bool")},
        {QLatin1Char('b'), QLatin1String("buffer")},
        {QLatin1Char('b'), QLatin1String("bytearray")},
        {QLatin1Char('b'), QLatin1String("bytes")},
        {QLatin1Char('c'), QLatin1String("callable")},
        {QLatin1Char('c'), QLatin1String("chr")},
        {QLatin1Char('c'), QLatin1String("classmethod")},
        {QLatin1Char('c'), QLatin1String("cmp")},
        {QLatin1Char('c'), QLatin1String("coerce")},
        {QLatin1Char('c'), QLatin1String("compile")},
        {QLatin1Char('c'), QLatin1String("complex")},
        {QLatin1Char('d'), QLatin1String("delattr")},
        {QLatin1Char('d'), QLatin1String("dict")},
        {QLatin1Char('d'), QLatin1String("dir")},
        {QLatin1Char('d'), QLatin1String("divmod")},
        {QLatin1Char('e'), QLatin1String("enumerate")},
        {QLatin1Char('e'), QLatin1String("eval")},
        {QLatin1Char('e'), QLatin1String("execfile")},
        {QLatin1Char('f'), QLatin1String("file")},
        {QLatin1Char('f'), QLatin1String("filter")},
        {QLatin1Char('f'), QLatin1String("float")},
        {QLatin1Char('f'), QLatin1String("format")},
        {QLatin1Char('f'), QLatin1String("frozenset")},
        {QLatin1Char('g'), QLatin1String("getattr")},
        {QLatin1Char('g'), QLatin1String("globals")},
        {QLatin1Char('h'), QLatin1String("hasattr")},
        {QLatin1Char('h'), QLatin1String("hash")},
        {QLatin1Char('h'), QLatin1String("help")},
        {QLatin1Char('h'), QLatin1String("hex")},
        {QLatin1Char('i'), QLatin1String("id")},
        {QLatin1Char('i'), QLatin1String("input")},
        {QLatin1Char('i'), QLatin1String("int")},
        {QLatin1Char('i'), QLatin1String("intern")},
        {QLatin1Char('i'), QLatin1String("isinstance")},
        {QLatin1Char('i'), QLatin1String("issubclass")},
        {QLatin1Char('i'), QLatin1String("iter")},
        {QLatin1Char('l'), QLatin1String("len")},
        {QLatin1Char('l'), QLatin1String("list")},
        {QLatin1Char('l'), QLatin1String("locals")},
        {QLatin1Char('l'), QLatin1String("long")},
        {QLatin1Char('m'), QLatin1String("map")},
        {QLatin1Char('m'), QLatin1String("max")},
        {QLatin1Char('m'), QLatin1String("memoryview")},
        {QLatin1Char('m'), QLatin1String("min")},
        {QLatin1Char('n'), QLatin1String("next")},
        {QLatin1Char('o'), QLatin1String("object")},
        {QLatin1Char('o'), QLatin1String("oct")},
        {QLatin1Char('o'), QLatin1String("open")},
        {QLatin1Char('o'), QLatin1String("ord")},
        {QLatin1Char('p'), QLatin1String("pow")},
        {QLatin1Char('p'), QLatin1String("property")},
        {QLatin1Char('r'), QLatin1String("range")},
        {QLatin1Char('r'), QLatin1String("raw_input")},
        {QLatin1Char('r'), QLatin1String("reduce")},
        {QLatin1Char('r'), QLatin1String("reload")},
        {QLatin1Char('r'), QLatin1String("repr")},
        {QLatin1Char('r'), QLatin1String("reversed")},
        {QLatin1Char('r'), QLatin1String("round")},
        {QLatin1Char('s'), QLatin1String("set")},
        {QLatin1Char('s'), QLatin1String("setattr")},
        {QLatin1Char('s'), QLatin1String("slice")},
        {QLatin1Char('s'), QLatin1String("sorted")},
        {QLatin1Char('s'), QLatin1String("staticmethod")},
        {QLatin1Char('s'), QLatin1String("str")},
        {QLatin1Char('s'), QLatin1String("sum")},
        {QLatin1Char('s'), QLatin1String("super")},
        {QLatin1Char('t'), QLatin1String("tuple")},
        {QLatin1Char('t'), QLatin1String("type")},
        {QLatin1Char('u'), QLatin1String("unichr")},
        {QLatin1Char('u'), QLatin1String("unicode")},
        {QLatin1Char('v'), QLatin1String("vars")},
        {QLatin1Char('x'), QLatin1String("xrange")},
        {QLatin1Char('z'), QLatin1String("zip")}
    };

    other = {
        {QLatin1Char('i'), QLatin1String("import")}
    };

}

void loadRustData(QMultiHash<QChar, QString> &types,
             QMultiHash<QChar, QString> &keywords,
             QMultiHash<QChar, QString> &builtin,
             QMultiHash<QChar, QString> &literals,
             QMultiHash<QChar, QString> &other){
    keywords = {
        {QLatin1Char('a'), QLatin1String("abstract")},
        {QLatin1Char('a'), QLatin1String("alignof")},
        {QLatin1Char('a'), QLatin1String("as")},
        {QLatin1Char('a'), QLatin1String("async")},
        {QLatin1Char('a'), QLatin1String("await")},
        {QLatin1Char('b'), QLatin1String("be")},
        {QLatin1Char('b'), QLatin1String("box")},
        {QLatin1Char('b'), QLatin1String("break")},
        {QLatin1Char('c'), QLatin1String("const")},
        {QLatin1Char('c'), QLatin1String("continue")},
        {QLatin1Char('c'), QLatin1String("crate")},
        {QLatin1Char('d'), QLatin1String("do")},
        {QLatin1Char('d'), QLatin1String("dyn")},
        {QLatin1Char('e'), QLatin1String("else")},
        {QLatin1Char('e'), QLatin1String("extern")},
        {QLatin1Char('f'), QLatin1String("final")},
        {QLatin1Char('f'), QLatin1String("fn")},
        {QLatin1Char('f'), QLatin1String("for")},
        {QLatin1Char('i'), QLatin1String("if")},
        {QLatin1Char('i'), QLatin1String("impl")},
        {QLatin1Char('i'), QLatin1String("in")},
        {QLatin1Char('l'), QLatin1String("let")},
        {QLatin1Char('l'), QLatin1String("loop")},
        {QLatin1Char('m'), QLatin1String("match")},
        {QLatin1Char('m'), QLatin1String("mod")},
        {QLatin1Char('m'), QLatin1String("move")},
        {QLatin1Char('m'), QLatin1String("mut")},
        {QLatin1Char('o'), QLatin1String("offsetof")},
        {QLatin1Char('o'), QLatin1String("once")},
        {QLatin1Char('o'), QLatin1String("override")},
        {QLatin1Char('p'), QLatin1String("priv")},
        {QLatin1Char('p'), QLatin1String("pub")},
        {QLatin1Char('p'), QLatin1String("pure")},
        {QLatin1Char('r'), QLatin1String("ref")},
        {QLatin1Char('r'), QLatin1String("return")},
        {QLatin1Char('s'), QLatin1String("sizeof")},
        {QLatin1Char('s'), QLatin1String("static")},
        {QLatin1Char('s'), QLatin1String("self")},
        {QLatin1Char('S'), QLatin1String("Self")},
        {QLatin1Char('s'), QLatin1String("super")},
        {QLatin1Char('t'), QLatin1String("trait")},
        {QLatin1Char('t'), QLatin1String("type")},
        {QLatin1Char('t'), QLatin1String("typeof")},
        {QLatin1Char('u'), QLatin1String("unsafe")},
        {QLatin1Char('u'), QLatin1String("unsized")},
        {QLatin1Char('u'), QLatin1String("use")},
        {QLatin1Char('v'), QLatin1String("virtual")},
        {QLatin1Char('w'), QLatin1String("where")},
        {QLatin1Char('w'), QLatin1String("while")},
        {QLatin1Char('y'), QLatin1String("yield")},
    };

    types = {
        {QLatin1Char('u'), QLatin1String("union")},
        {QLatin1Char('e'), QLatin1String("enum")},
        {QLatin1Char('s'), QLatin1String("struct")},

        {QLatin1Char('i'), QLatin1String("i8")},
        {QLatin1Char('i'), QLatin1String("i16")},
        {QLatin1Char('i'), QLatin1String("i32")},
        {QLatin1Char('i'), QLatin1String("i64")},
        {QLatin1Char('i'), QLatin1String("i128")},
        {QLatin1Char('i'), QLatin1String("isize")},
        {QLatin1Char('u'), QLatin1String("u8")},
        {QLatin1Char('u'), QLatin1String("u16")},
        {QLatin1Char('u'), QLatin1String("u32")},
        {QLatin1Char('u'), QLatin1String("u64")},
        {QLatin1Char('u'), QLatin1String("u128")},
        {QLatin1Char('u'), QLatin1String("usize")},
        {QLatin1Char('f'), QLatin1String("f32")},
        {QLatin1Char('f'), QLatin1String("f64")},
        {QLatin1Char('s'), QLatin1String("str")},
        {QLatin1Char('c'), QLatin1String("char")},
        {QLatin1Char('b'), QLatin1String("bool")},
        {QLatin1Char('B'), QLatin1String("Box")},
        {QLatin1Char('O'), QLatin1String("Option")},
        {QLatin1Char('R'), QLatin1String("Result")},
        {QLatin1Char('S'), QLatin1String("String")},
        {QLatin1Char('V'), QLatin1String("Vec")}
    };

    literals = {
        {QLatin1Char('f'), QLatin1String("false")},
        {QLatin1Char('t'), QLatin1String("true")}
    };

    builtin = {

    };

    other = {
        {QLatin1Char('a'), QLatin1String("assert!")},
        {QLatin1Char('a'), QLatin1String("assert_eq!")},
        {QLatin1Char('b'), QLatin1String("bitflags!")},
        {QLatin1Char('b'), QLatin1String("bytes!")},
        {QLatin1Char('c'), QLatin1String("cfg!")},
        {QLatin1Char('c'), QLatin1String("col!")},
        {QLatin1Char('c'), QLatin1String("concat!")},
        {QLatin1Char('c'), QLatin1String("concat_idents!")},
        {QLatin1Char('d'), QLatin1String("debug_assert!")},
        {QLatin1Char('d'), QLatin1String("debug_assert_eq!")},
        {QLatin1Char('e'), QLatin1String("env!")},
        {QLatin1Char('p'), QLatin1String("panic!")},
        {QLatin1Char('f'), QLatin1String("file!")},
        {QLatin1Char('f'), QLatin1String("format!")},
        {QLatin1Char('f'), QLatin1String("format_args!")},
        {QLatin1Char('i'), QLatin1String("include_bin!")},
        {QLatin1Char('i'), QLatin1String("include_str!")},
        {QLatin1Char('l'), QLatin1String("line!")},
        {QLatin1Char('l'), QLatin1String("local_data_key!")},
        {QLatin1Char('m'), QLatin1String("module_path!")},
        {QLatin1Char('o'), QLatin1String("option_env!")},
        {QLatin1Char('p'), QLatin1String("print!")},
        {QLatin1Char('p'), QLatin1String("println!")},
        {QLatin1Char('s'), QLatin1String("select!")},
        {QLatin1Char('s'), QLatin1String("stringify!")},
        {QLatin1Char('t'), QLatin1String("try!")},
        {QLatin1Char('u'), QLatin1String("unimplemented!")},
        {QLatin1Char('u'), QLatin1String("unreachable!")},
        {QLatin1Char('v'), QLatin1String("vec!")},
        {QLatin1Char('w'), QLatin1String("write!")},
        {QLatin1Char('w'), QLatin1String("writeln!")},
        {QLatin1Char('m'), QLatin1String("macro_rules!")},
        {QLatin1Char('a'), QLatin1String("assert_ne!")},
        {QLatin1Char('d'), QLatin1String("debug_assert_ne!")}
    };

}

void loadJavaData(QMultiHash<QChar, QString> &types,
             QMultiHash<QChar, QString> &keywords,
             QMultiHash<QChar, QString> &builtin,
             QMultiHash<QChar, QString> &literals,
             QMultiHash<QChar, QString> &other){
    keywords = {
        {QLatin1Char('a'), QLatin1String("abstract")},
        {QLatin1Char('a'), QLatin1String("assert")},
        {QLatin1Char('b'), QLatin1String("break")},
        {QLatin1Char('c'), QLatin1String("case")},
        {QLatin1Char('c'), QLatin1String("catch")},
        {QLatin1Char('c'), QLatin1String("const")},
        {QLatin1Char('c'), QLatin1String("continue")},
        {QLatin1Char('d'), QLatin1String("default")},
        {QLatin1Char('d'), QLatin1String("do")},
        {QLatin1Char('e'), QLatin1String("else")},
        {QLatin1Char('e'), QLatin1String("exports")},
        {QLatin1Char('e'), QLatin1String("extends")},
        {QLatin1Char('f'), QLatin1String("final")},
        {QLatin1Char('f'), QLatin1String("finally")},
        {QLatin1Char('f'), QLatin1String("for")},
        {QLatin1Char('g'), QLatin1String("goto")},
        {QLatin1Char('i'), QLatin1String("if")},
        {QLatin1Char('i'), QLatin1String("implements")},
        {QLatin1Char('i'), QLatin1String("import")},
        {QLatin1Char('i'), QLatin1String("instanceof")},
        {QLatin1Char('i'), QLatin1String("interface")},
        {QLatin1Char('l'), QLatin1String("long")},
        {QLatin1Char('m'), QLatin1String("module")},
        {QLatin1Char('n'), QLatin1String("native")},
        {QLatin1Char('n'), QLatin1String("new")},
        {QLatin1Char('n'), QLatin1String("null")},
        {QLatin1Char('o'), QLatin1String("open")},
        {QLatin1Char('o'), QLatin1String("opens")},
        {QLatin1Char('p'), QLatin1String("package")},
        {QLatin1Char('p'), QLatin1String("private")},
        {QLatin1Char('p'), QLatin1String("protected")},
        {QLatin1Char('p'), QLatin1String("provides")},
        {QLatin1Char('p'), QLatin1String("public")},
        {QLatin1Char('r'), QLatin1String("requires")},
        {QLatin1Char('r'), QLatin1String("return")},
        {QLatin1Char('s'), QLatin1String("static")},
        {QLatin1Char('s'), QLatin1String("strictfp")},
        {QLatin1Char('s'), QLatin1String("super")},
        {QLatin1Char('s'), QLatin1String("switch")},
        {QLatin1Char('s'), QLatin1String("synchronized")},
        {QLatin1Char('t'), QLatin1String("this")},
        {QLatin1Char('t'), QLatin1String("throw")},
        {QLatin1Char('t'), QLatin1String("throws")},
        {QLatin1Char('t'), QLatin1String("to")},
        {QLatin1Char('t'), QLatin1String("transient")},
        {QLatin1Char('t'), QLatin1String("transitive")},
        {QLatin1Char('t'), QLatin1String("try")},
        {QLatin1Char('u'), QLatin1String("uses")},
        {QLatin1Char('v'), QLatin1String("var")},
        {QLatin1Char('v'), QLatin1String("volatile")},
        {QLatin1Char('w'), QLatin1String("while")},
        {QLatin1Char('w'), QLatin1String("with")},
        {QLatin1Char('y'), QLatin1String("yield")}
    };

    types = {
        {QLatin1Char('v'), QLatin1String("void")},
        {QLatin1Char('f'), QLatin1String("float")},
        {QLatin1Char('b'), QLatin1String("boolean")},
        {QLatin1Char('b'), QLatin1String("byte")},
        {QLatin1Char('i'), QLatin1String("int")},
        {QLatin1Char('c'), QLatin1String("char")},
        {QLatin1Char('c'), QLatin1String("class")},
        {QLatin1Char('d'), QLatin1String("double")},
        {QLatin1Char('e'), QLatin1String("enum")},
        {QLatin1Char('s'), QLatin1String("short")},

    };

    literals = {
        {QLatin1Char('f'), QLatin1String("false")},
        {QLatin1Char('t'), QLatin1String("true")}
    };

    builtin = {

    };

    other = {

    };

}

void loadCSharpData(QMultiHash<QChar, QString> &types,
             QMultiHash<QChar, QString> &keywords,
             QMultiHash<QChar, QString> &builtin,
             QMultiHash<QChar, QString> &literals,
             QMultiHash<QChar, QString> &other){
    keywords = {
        {QLatin1Char('a'), QLatin1String("abstract")},
        {QLatin1Char('a'), QLatin1String("add")},
        {QLatin1Char('a'), QLatin1String("alias")},
        {QLatin1Char('a'), QLatin1String("as")},
        {QLatin1Char('a'), QLatin1String("ascending")},
        {QLatin1Char('a'), QLatin1String("async")},
        {QLatin1Char('a'), QLatin1String("await")},
        {QLatin1Char('b'), QLatin1String("base")},
        {QLatin1Char('b'), QLatin1String("break")},
        {QLatin1Char('c'), QLatin1String("case")},
        {QLatin1Char('c'), QLatin1String("catch")},
        {QLatin1Char('c'), QLatin1String("checked")},
        {QLatin1Char('c'), QLatin1String("const")},
        {QLatin1Char('c'), QLatin1String("continue")},
        {QLatin1Char('d'), QLatin1String("decimal")},
        {QLatin1Char('d'), QLatin1String("default")},
        {QLatin1Char('d'), QLatin1String("delegate")},
        {QLatin1Char('d'), QLatin1String("descending")},
        {QLatin1Char('d'), QLatin1String("do")},
        {QLatin1Char('d'), QLatin1String("dynamic")},
        {QLatin1Char('e'), QLatin1String("else")},
        {QLatin1Char('e'), QLatin1String("event")},
        {QLatin1Char('e'), QLatin1String("explicit")},
        {QLatin1Char('e'), QLatin1String("extern")},
        {QLatin1Char('f'), QLatin1String("finally")},
        {QLatin1Char('f'), QLatin1String("fixed")},
        {QLatin1Char('f'), QLatin1String("for")},
        {QLatin1Char('f'), QLatin1String("foreach")},
        {QLatin1Char('f'), QLatin1String("from")},
        {QLatin1Char('g'), QLatin1String("get")},
        {QLatin1Char('g'), QLatin1String("global")},
        {QLatin1Char('g'), QLatin1String("goto")},
        {QLatin1Char('g'), QLatin1String("group")},
        {QLatin1Char('i'), QLatin1String("if")},
        {QLatin1Char('i'), QLatin1String("implicit")},
        {QLatin1Char('i'), QLatin1String("in")},
        {QLatin1Char('i'), QLatin1String("interface")},
        {QLatin1Char('i'), QLatin1String("internal")},
        {QLatin1Char('i'), QLatin1String("into")},
        {QLatin1Char('i'), QLatin1String("is")},
        {QLatin1Char('j'), QLatin1String("join")},
        {QLatin1Char('l'), QLatin1String("let")},
        {QLatin1Char('l'), QLatin1String("lock")},
        {QLatin1Char('l'), QLatin1String("long")},
        {QLatin1Char('n'), QLatin1String("namespace")},
        {QLatin1Char('n'), QLatin1String("new")},
        {QLatin1Char('o'), QLatin1String("object")},
        {QLatin1Char('o'), QLatin1String("operator")},
        {QLatin1Char('o'), QLatin1String("orderby")},
        {QLatin1Char('o'), QLatin1String("out")},
        {QLatin1Char('o'), QLatin1String("override")},
        {QLatin1Char('p'), QLatin1String("params")},
        {QLatin1Char('p'), QLatin1String("partial")},
        {QLatin1Char('p'), QLatin1String("private")},
        {QLatin1Char('p'), QLatin1String("protected")},
        {QLatin1Char('p'), QLatin1String("public")},
        {QLatin1Char('r'), QLatin1String("readonly")},
        {QLatin1Char('r'), QLatin1String("ref")},
        {QLatin1Char('r'), QLatin1String("remove")},
        {QLatin1Char('r'), QLatin1String("return")},
        {QLatin1Char('s'), QLatin1String("sealed")},
        {QLatin1Char('s'), QLatin1String("select")},
        {QLatin1Char('s'), QLatin1String("set")},
        {QLatin1Char('s'), QLatin1String("sizeof")},
        {QLatin1Char('s'), QLatin1String("stackalloc")},
        {QLatin1Char('s'), QLatin1String("static")},
        {QLatin1Char('s'), QLatin1String("switch")},
        {QLatin1Char('t'), QLatin1String("this")},
        {QLatin1Char('t'), QLatin1String("throw")},
        {QLatin1Char('t'), QLatin1String("try")},
        {QLatin1Char('t'), QLatin1String("typeof")},
        {QLatin1Char('u'), QLatin1String("unchecked")},
        {QLatin1Char('u'), QLatin1String("unsafe")},
        {QLatin1Char('u'), QLatin1String("using")},
        {QLatin1Char('v'), QLatin1String("value")},
        {QLatin1Char('v'), QLatin1String("virtual")},
        {QLatin1Char('v'), QLatin1String("volatile")},
        {QLatin1Char('w'), QLatin1String("where")},
        {QLatin1Char('w'), QLatin1String("while")},
        {QLatin1Char('y'), QLatin1String("yield")}
    };

    types = {
        {QLatin1Char('b'), QLatin1String("bool")},
        {QLatin1Char('b'), QLatin1String("byte")},
        {QLatin1Char('c'), QLatin1String("char")},
        {QLatin1Char('c'), QLatin1String("class")},
        {QLatin1Char('d'), QLatin1String("double")},
        {QLatin1Char('e'), QLatin1String("enum")},
        {QLatin1Char('f'), QLatin1String("float")},
        {QLatin1Char('i'), QLatin1String("int")},
        {QLatin1Char('s'), QLatin1String("sbyte")},
        {QLatin1Char('s'), QLatin1String("short")},
        {QLatin1Char('s'), QLatin1String("string")},
        {QLatin1Char('s'), QLatin1String("struct")},
        {QLatin1Char('u'), QLatin1String("uint")},
        {QLatin1Char('u'), QLatin1String("ulong")},
        {QLatin1Char('u'), QLatin1String("ushort")},
        {QLatin1Char('v'), QLatin1String("var")},
        {QLatin1Char('v'), QLatin1String("void")},
    };

    literals = {
        {QLatin1Char('f'), QLatin1String("false")},
        {QLatin1Char('t'), QLatin1String("true")},
        {QLatin1Char('n'), QLatin1String("null")}
    };

    builtin = {

    };

    other = {
        {QLatin1Char('d'), QLatin1String("define")},
        {QLatin1Char('e'), QLatin1String("elif")},
        {QLatin1Char('e'), QLatin1String("else")},
        {QLatin1Char('e'), QLatin1String("endif")},
        {QLatin1Char('e'), QLatin1String("endregion")},
        {QLatin1Char('e'), QLatin1String("error")},
        {QLatin1Char('i'), QLatin1String("if")},
        {QLatin1Char('l'), QLatin1String("line")},
        {QLatin1Char('p'), QLatin1String("pragma")},
        {QLatin1Char('r'), QLatin1String("region")},
        {QLatin1Char('u'), QLatin1String("undef")},
        {QLatin1Char('w'), QLatin1String("warning")}
    };

}

void loadGoData(QMultiHash<QChar, QString> &types,
             QMultiHash<QChar, QString> &keywords,
             QMultiHash<QChar, QString> &builtin,
             QMultiHash<QChar, QString> &literals,
             QMultiHash<QChar, QString> &other){
    keywords = {
        {QLatin1Char('b'), QLatin1String("break")},
        {QLatin1Char('c'), QLatin1String("case")},
        {QLatin1Char('c'), QLatin1String("chan")},
        {QLatin1Char('c'), QLatin1String("const")},
        {QLatin1Char('c'), QLatin1String("continue")},
        {QLatin1Char('d'), QLatin1String("default")},
        {QLatin1Char('d'), QLatin1String("defer")},
        {QLatin1Char('e'), QLatin1String("else")},
        {QLatin1Char('f'), QLatin1String("fallthrough")},
        {QLatin1Char('f'), QLatin1String("for")},
        {QLatin1Char('f'), QLatin1String("func")},
        {QLatin1Char('g'), QLatin1String("go")},
        {QLatin1Char('t'), QLatin1String("to")},
        {QLatin1Char('i'), QLatin1String("if")},
        {QLatin1Char('i'), QLatin1String("import")},
        {QLatin1Char('i'), QLatin1String("interface")},
        {QLatin1Char('p'), QLatin1String("package")},
        {QLatin1Char('r'), QLatin1String("range")},
        {QLatin1Char('r'), QLatin1String("return")},
        {QLatin1Char('s'), QLatin1String("select")},
        {QLatin1Char('s'), QLatin1String("struct")},
        {QLatin1Char('s'), QLatin1String("switch")},
        {QLatin1Char('t'), QLatin1String("type")},
    };

    types = {
        {QLatin1Char('m'), QLatin1String("map")},
        {QLatin1Char('s'), QLatin1String("struct")},
        {QLatin1Char('v'), QLatin1String("var")},
        {QLatin1Char('b'), QLatin1String("bool")},
        {QLatin1Char('b'), QLatin1String("byte")},
        {QLatin1Char('c'), QLatin1String("complex64")},
        {QLatin1Char('c'), QLatin1String("complex128")},
        {QLatin1Char('f'), QLatin1String("float32")},
        {QLatin1Char('f'), QLatin1String("float64")},
        {QLatin1Char('i'), QLatin1String("int8")},
        {QLatin1Char('i'), QLatin1String("int16")},
        {QLatin1Char('i'), QLatin1String("int32")},
        {QLatin1Char('i'), QLatin1String("int64")},
        {QLatin1Char('s'), QLatin1String("string")},
        {QLatin1Char('u'), QLatin1String("uint8")},
        {QLatin1Char('u'), QLatin1String("uint16")},
        {QLatin1Char('u'), QLatin1String("uint32")},
        {QLatin1Char('u'), QLatin1String("uint64")},
        {QLatin1Char('i'), QLatin1String("int")},
        {QLatin1Char('u'), QLatin1String("uint")},
        {QLatin1Char('u'), QLatin1String("uintptr")},
        {QLatin1Char('r'), QLatin1String("rune")}
    };

    literals = {
        {QLatin1Char('f'), QLatin1String("false")},
        {QLatin1Char('t'), QLatin1String("true")},
        {QLatin1Char('n'), QLatin1String("nil")},
        {QLatin1Char('i'), QLatin1String("iota")}
    };

    builtin = {
        {QLatin1Char('a'), QLatin1String("append")},
        {QLatin1Char('c'), QLatin1String("cap")},
        {QLatin1Char('c'), QLatin1String("close")},
        {QLatin1Char('c'), QLatin1String("complex")},
        {QLatin1Char('c'), QLatin1String("copy")},
        {QLatin1Char('i'), QLatin1String("imag")},
        {QLatin1Char('l'), QLatin1String("len")},
        {QLatin1Char('m'), QLatin1String("make")},
        {QLatin1Char('n'), QLatin1String("new")},
        {QLatin1Char('p'), QLatin1String("panic")},
        {QLatin1Char('p'), QLatin1String("print")},
        {QLatin1Char('p'), QLatin1String("println")},
        {QLatin1Char('r'), QLatin1String("real")},
        {QLatin1Char('r'), QLatin1String("recover")},
        {QLatin1Char('d'), QLatin1String("delete")}
    };

    other = {

    };

}

void loadVData(QMultiHash<QChar, QString> &types,
             QMultiHash<QChar, QString> &keywords,
             QMultiHash<QChar, QString> &builtin,
             QMultiHash<QChar, QString> &literals,
             QMultiHash<QChar, QString> &other){
    keywords = {
        {QLatin1Char('b'), QLatin1String("break")},
        {QLatin1Char('c'), QLatin1String("const")},
        {QLatin1Char('c'), QLatin1String("continue")},
        {QLatin1Char('d'), QLatin1String("defer")},
        {QLatin1Char('e'), QLatin1String("else")},
        {QLatin1Char('f'), QLatin1String("for")},
        {QLatin1Char('f'), QLatin1String("fn")},
        {QLatin1Char('g'), QLatin1String("go")},
        {QLatin1Char('g'), QLatin1String("goto")},
        {QLatin1Char('i'), QLatin1String("if")},
        {QLatin1Char('i'), QLatin1String("import")},
        {QLatin1Char('i'), QLatin1String("interface")},
        {QLatin1Char('r'), QLatin1String("return")},
        {QLatin1Char('s'), QLatin1String("struct")},
        {QLatin1Char('s'), QLatin1String("switch")},
        {QLatin1Char('t'), QLatin1String("type")},
        {QLatin1Char('p'), QLatin1String("pub")},
        {QLatin1Char('o'), QLatin1String("or")},
        {QLatin1Char('n'), QLatin1String("none")}
    };

    types = {
        {QLatin1Char('m'), QLatin1String("map")},
        {QLatin1Char('s'), QLatin1String("struct")},
        {QLatin1Char('b'), QLatin1String("bool")},
        {QLatin1Char('b'), QLatin1String("byte")},
        {QLatin1Char('f'), QLatin1String("f32")},
        {QLatin1Char('f'), QLatin1String("f64")},
        {QLatin1Char('i'), QLatin1String("i8")},
        {QLatin1Char('i'), QLatin1String("i16")},
        {QLatin1Char('i'), QLatin1String("int")},
        {QLatin1Char('i'), QLatin1String("i64")},
        {QLatin1Char('i'), QLatin1String("i128")},
        {QLatin1Char('s'), QLatin1String("string")},
        {QLatin1Char('u'), QLatin1String("u16")},
        {QLatin1Char('u'), QLatin1String("u32")},
        {QLatin1Char('u'), QLatin1String("u64")},
        {QLatin1Char('u'), QLatin1String("u128")},
        {QLatin1Char('u'), QLatin1String("byteptr")},
        {QLatin1Char('u'), QLatin1String("voidptr")},
        {QLatin1Char('r'), QLatin1String("rune")}
    };

    literals = {
        {QLatin1Char('f'), QLatin1String("false")},
        {QLatin1Char('t'), QLatin1String("true")},
    };

    builtin = {
    };

    other = {

    };

}

void loadSQLData(QMultiHash<QChar, QString> &types,
             QMultiHash<QChar, QString> &keywords,
             QMultiHash<QChar, QString> &builtin,
             QMultiHash<QChar, QString> &literals,
             QMultiHash<QChar, QString> &other){
    keywords = {
        {QLatin1Char('A'), QLatin1String("ACTION")},
        {QLatin1Char('A'), QLatin1String("ADD")},
        {QLatin1Char('A'), QLatin1String("AFTER")},
        {QLatin1Char('A'), QLatin1String("ALGORITHM")},
        {QLatin1Char('A'), QLatin1String("ALL")},
        {QLatin1Char('A'), QLatin1String("ALTER")},
        {QLatin1Char('A'), QLatin1String("ANALYZE")},
        {QLatin1Char('A'), QLatin1String("ANY")},
        {QLatin1Char('A'), QLatin1String("APPLY")},
        {QLatin1Char('A'), QLatin1String("AS")},
        {QLatin1Char('A'), QLatin1String("ASC")},
        {QLatin1Char('A'), QLatin1String("AUTHORIZATION")},
        {QLatin1Char('A'), QLatin1String("AUTO_INCREMENT")},
        {QLatin1Char('B'), QLatin1String("BACKUP")},
        {QLatin1Char('B'), QLatin1String("BDB")},
        {QLatin1Char('B'), QLatin1String("BEGIN")},
        {QLatin1Char('B'), QLatin1String("BERKELEYDB")},
        {QLatin1Char('B'), QLatin1String("BIGINT")},
        {QLatin1Char('B'), QLatin1String("BINARY")},
        {QLatin1Char('B'), QLatin1String("BIT")},
        {QLatin1Char('B'), QLatin1String("BLOB")},
        {QLatin1Char('B'), QLatin1String("BOOL")},
        {QLatin1Char('B'), QLatin1String("BOOLEAN")},
        {QLatin1Char('B'), QLatin1String("BREAK")},
        {QLatin1Char('B'), QLatin1String("BROWSE")},
        {QLatin1Char('B'), QLatin1String("BTREE")},
        {QLatin1Char('B'), QLatin1String("BULK")},
        {QLatin1Char('B'), QLatin1String("BY")},
        {QLatin1Char('C'), QLatin1String("CALL")},
        {QLatin1Char('C'), QLatin1String("CASCADED")},
        {QLatin1Char('C'), QLatin1String("CASE")},
        {QLatin1Char('C'), QLatin1String("CHAIN")},
        {QLatin1Char('C'), QLatin1String("CHARACTER")},
        {QLatin1Char('S'), QLatin1String("SET")},
        {QLatin1Char('C'), QLatin1String("CHECKPOINT")},
        {QLatin1Char('C'), QLatin1String("CLOSE")},
        {QLatin1Char('C'), QLatin1String("CLUSTERED")},
        {QLatin1Char('C'), QLatin1String("COALESCE")},
        {QLatin1Char('C'), QLatin1String("COLLATE")},
        {QLatin1Char('C'), QLatin1String("COLUMNS")},
        {QLatin1Char('C'), QLatin1String("COMMENT")},
        {QLatin1Char('C'), QLatin1String("COMMITTED")},
        {QLatin1Char('C'), QLatin1String("COMPUTE")},
        {QLatin1Char('C'), QLatin1String("CONNECT")},
        {QLatin1Char('C'), QLatin1String("CONSISTENT")},
        {QLatin1Char('C'), QLatin1String("CONSTRAINT")},
        {QLatin1Char('C'), QLatin1String("CONTAINSTABLE")},
        {QLatin1Char('C'), QLatin1String("CONTINUE")},
        {QLatin1Char('C'), QLatin1String("CONVERT")},
        {QLatin1Char('C'), QLatin1String("CREATE")},
        {QLatin1Char('C'), QLatin1String("CROSS")},
        {QLatin1Char('C'), QLatin1String("CURRENT_DATE")},
        {QLatin1Char('_'), QLatin1String("_TIME")},
        {QLatin1Char('_'), QLatin1String("_TIMESTAMP")},
        {QLatin1Char('_'), QLatin1String("_USER")},
        {QLatin1Char('C'), QLatin1String("CURSOR")},
        {QLatin1Char('C'), QLatin1String("CYCLE")},
        {QLatin1Char('D'), QLatin1String("DATABASES")},
        {QLatin1Char('D'), QLatin1String("DATETIME")},
        {QLatin1Char('D'), QLatin1String("DAY")},
        {QLatin1Char('D'), QLatin1String("DBCC")},
        {QLatin1Char('D'), QLatin1String("DEALLOCATE")},
        {QLatin1Char('D'), QLatin1String("DEC")},
        {QLatin1Char('D'), QLatin1String("DECIMAL")},
        {QLatin1Char('D'), QLatin1String("DECLARE")},
        {QLatin1Char('D'), QLatin1String("DEFAULT")},
        {QLatin1Char('D'), QLatin1String("DEFINER")},
        {QLatin1Char('D'), QLatin1String("DELAYED")},
        {QLatin1Char('D'), QLatin1String("DELETE")},
        {QLatin1Char('D'), QLatin1String("DELIMITERS")},
        {QLatin1Char('D'), QLatin1String("DENY")},
        {QLatin1Char('D'), QLatin1String("DESC")},
        {QLatin1Char('D'), QLatin1String("DESCRIBE")},
        {QLatin1Char('D'), QLatin1String("DETERMINISTIC")},
        {QLatin1Char('D'), QLatin1String("DISABLE")},
        {QLatin1Char('D'), QLatin1String("DISCARD")},
        {QLatin1Char('D'), QLatin1String("DISK")},
        {QLatin1Char('D'), QLatin1String("DISTINCT")},
        {QLatin1Char('D'), QLatin1String("DISTINCTROW")},
        {QLatin1Char('D'), QLatin1String("DISTRIBUTED")},
        {QLatin1Char('D'), QLatin1String("DO")},
        {QLatin1Char('D'), QLatin1String("DOUBLE")},
        {QLatin1Char('D'), QLatin1String("DROP")},
        {QLatin1Char('D'), QLatin1String("DUMMY")},
        {QLatin1Char('D'), QLatin1String("DUMPFILE")},
        {QLatin1Char('D'), QLatin1String("DUPLICATE")},
        {QLatin1Char('E'), QLatin1String("ELSEIF")},
        {QLatin1Char('E'), QLatin1String("ENABLE")},
        {QLatin1Char('E'), QLatin1String("ENCLOSED")},
        {QLatin1Char('E'), QLatin1String("END")},
        {QLatin1Char('E'), QLatin1String("ENGINE")},
        {QLatin1Char('E'), QLatin1String("ENUM")},
        {QLatin1Char('E'), QLatin1String("ERRLVL")},
        {QLatin1Char('E'), QLatin1String("ERRORS")},
        {QLatin1Char('E'), QLatin1String("ESCAPED")},
        {QLatin1Char('E'), QLatin1String("EXCEPT")},
        {QLatin1Char('E'), QLatin1String("EXECUTE")},
        {QLatin1Char('E'), QLatin1String("EXISTS")},
        {QLatin1Char('E'), QLatin1String("EXIT")},
        {QLatin1Char('E'), QLatin1String("EXPLAIN")},
        {QLatin1Char('E'), QLatin1String("EXTENDED")},
        {QLatin1Char('F'), QLatin1String("FETCH")},
        {QLatin1Char('F'), QLatin1String("FIELDS")},
        {QLatin1Char('F'), QLatin1String("FILE")},
        {QLatin1Char('F'), QLatin1String("FILLFACTOR")},
        {QLatin1Char('F'), QLatin1String("FIRST")},
        {QLatin1Char('F'), QLatin1String("FIXED")},
        {QLatin1Char('F'), QLatin1String("FLOAT")},
        {QLatin1Char('F'), QLatin1String("FOLLOWING")},
        {QLatin1Char('F'), QLatin1String("FOR")},
        {QLatin1Char('E'), QLatin1String("EACH")},
        {QLatin1Char('R'), QLatin1String("ROW")},
        {QLatin1Char('F'), QLatin1String("FORCE")},
        {QLatin1Char('F'), QLatin1String("FOREIGN")},
        {QLatin1Char('F'), QLatin1String("FREETEXTTABLE")},
        {QLatin1Char('F'), QLatin1String("FROM")},
        {QLatin1Char('F'), QLatin1String("FULL")},
        {QLatin1Char('F'), QLatin1String("FUNCTION")},
        {QLatin1Char('G'), QLatin1String("GEOMETRYCOLLECTION")},
        {QLatin1Char('G'), QLatin1String("GLOBAL")},
        {QLatin1Char('G'), QLatin1String("GOTO")},
        {QLatin1Char('G'), QLatin1String("GRANT")},
        {QLatin1Char('G'), QLatin1String("GROUP")},
        {QLatin1Char('H'), QLatin1String("HANDLER")},
        {QLatin1Char('H'), QLatin1String("HASH")},
        {QLatin1Char('H'), QLatin1String("HAVING")},
        {QLatin1Char('H'), QLatin1String("HOLDLOCK")},
        {QLatin1Char('H'), QLatin1String("HOUR")},
        {QLatin1Char('I'), QLatin1String("IDENTITY_INSERT")},
        {QLatin1Char('C'), QLatin1String("COL")},
        {QLatin1Char('I'), QLatin1String("IF")},
        {QLatin1Char('I'), QLatin1String("IGNORE")},
        {QLatin1Char('I'), QLatin1String("IMPORT")},
        {QLatin1Char('I'), QLatin1String("INDEX")},
        {QLatin1Char('I'), QLatin1String("INFILE")},
        {QLatin1Char('I'), QLatin1String("INNER")},
        {QLatin1Char('I'), QLatin1String("INNODB")},
        {QLatin1Char('I'), QLatin1String("INOUT")},
        {QLatin1Char('I'), QLatin1String("INSERT")},
        {QLatin1Char('I'), QLatin1String("INT")},
        {QLatin1Char('I'), QLatin1String("INTEGER")},
        {QLatin1Char('I'), QLatin1String("INTERSECT")},
        {QLatin1Char('I'), QLatin1String("INTERVAL")},
        {QLatin1Char('I'), QLatin1String("INTO")},
        {QLatin1Char('I'), QLatin1String("INVOKER")},
        {QLatin1Char('I'), QLatin1String("ISOLATION")},
        {QLatin1Char('I'), QLatin1String("ITERATE")},
        {QLatin1Char('J'), QLatin1String("JOIN")},
        {QLatin1Char('K'), QLatin1String("KEYS")},
        {QLatin1Char('K'), QLatin1String("KILL")},
        {QLatin1Char('L'), QLatin1String("LANGUAGE")},
        {QLatin1Char('L'), QLatin1String("LAST")},
        {QLatin1Char('L'), QLatin1String("LEAVE")},
        {QLatin1Char('L'), QLatin1String("LEFT")},
        {QLatin1Char('L'), QLatin1String("LEVEL")},
        {QLatin1Char('L'), QLatin1String("LIMIT")},
        {QLatin1Char('L'), QLatin1String("LINENO")},
        {QLatin1Char('L'), QLatin1String("LINES")},
        {QLatin1Char('L'), QLatin1String("LINESTRING")},
        {QLatin1Char('L'), QLatin1String("LOAD")},
        {QLatin1Char('L'), QLatin1String("LOCAL")},
        {QLatin1Char('L'), QLatin1String("LOCK")},
        {QLatin1Char('L'), QLatin1String("LONGBLOB")},
        {QLatin1Char('T'), QLatin1String("TEXT")},
        {QLatin1Char('L'), QLatin1String("LOOP")},
        {QLatin1Char('M'), QLatin1String("MATCHED")},
        {QLatin1Char('M'), QLatin1String("MEDIUMBLOB")},
        {QLatin1Char('I'), QLatin1String("INT")},
        {QLatin1Char('T'), QLatin1String("TEXT")},
        {QLatin1Char('M'), QLatin1String("MERGE")},
        {QLatin1Char('M'), QLatin1String("MIDDLEINT")},
        {QLatin1Char('M'), QLatin1String("MINUTE")},
        {QLatin1Char('M'), QLatin1String("MODE")},
        {QLatin1Char('M'), QLatin1String("MODIFIES")},
        {QLatin1Char('M'), QLatin1String("MODIFY")},
        {QLatin1Char('M'), QLatin1String("MONTH")},
        {QLatin1Char('M'), QLatin1String("MULTILINESTRING")},
        {QLatin1Char('P'), QLatin1String("POINT")},
        {QLatin1Char('P'), QLatin1String("POLYGON")},
        {QLatin1Char('N'), QLatin1String("NATIONAL")},
        {QLatin1Char('N'), QLatin1String("NATURAL")},
        {QLatin1Char('N'), QLatin1String("NCHAR")},
        {QLatin1Char('N'), QLatin1String("NEXT")},
        {QLatin1Char('N'), QLatin1String("NO")},
        {QLatin1Char('N'), QLatin1String("NONCLUSTERED")},
        {QLatin1Char('N'), QLatin1String("NULLIF")},
        {QLatin1Char('N'), QLatin1String("NUMERIC")},
        {QLatin1Char('O'), QLatin1String("OFF")},
        {QLatin1Char('O'), QLatin1String("OFFSETS")},
        {QLatin1Char('O'), QLatin1String("ON")},
        {QLatin1Char('O'), QLatin1String("OPENDATASOURCE")},
        {QLatin1Char('Q'), QLatin1String("QUERY")},
        {QLatin1Char('R'), QLatin1String("ROWSET")},
        {QLatin1Char('O'), QLatin1String("OPTIMIZE")},
        {QLatin1Char('O'), QLatin1String("OPTIONALLY")},
        {QLatin1Char('O'), QLatin1String("ORDER")},
        {QLatin1Char('O'), QLatin1String("OUTER")},
        {QLatin1Char('F'), QLatin1String("FILE")},
        {QLatin1Char('O'), QLatin1String("OVER")},
        {QLatin1Char('P'), QLatin1String("PARTIAL")},
        {QLatin1Char('P'), QLatin1String("PARTITION")},
        {QLatin1Char('P'), QLatin1String("PERCENT")},
        {QLatin1Char('P'), QLatin1String("PIVOT")},
        {QLatin1Char('P'), QLatin1String("PLAN")},
        {QLatin1Char('P'), QLatin1String("POINT")},
        {QLatin1Char('P'), QLatin1String("POLYGON")},
        {QLatin1Char('P'), QLatin1String("PRECEDING")},
        {QLatin1Char('P'), QLatin1String("PRECISION")},
        {QLatin1Char('P'), QLatin1String("PREPARE")},
        {QLatin1Char('P'), QLatin1String("PREV")},
        {QLatin1Char('P'), QLatin1String("PRIMARY")},
        {QLatin1Char('P'), QLatin1String("PRINT")},
        {QLatin1Char('P'), QLatin1String("PRIVILEGES")},
        {QLatin1Char('P'), QLatin1String("PROCEDURE")},
        {QLatin1Char('P'), QLatin1String("PUBLIC")},
        {QLatin1Char('P'), QLatin1String("PURGE")},
        {QLatin1Char('Q'), QLatin1String("QUICK")},
        {QLatin1Char('R'), QLatin1String("RAISERROR")},
        {QLatin1Char('R'), QLatin1String("READS")},
        {QLatin1Char('R'), QLatin1String("REAL")},
        {QLatin1Char('R'), QLatin1String("RECONFIGURE")},
        {QLatin1Char('R'), QLatin1String("REFERENCES")},
        {QLatin1Char('R'), QLatin1String("RELEASE")},
        {QLatin1Char('R'), QLatin1String("RENAME")},
        {QLatin1Char('R'), QLatin1String("REPEATABLE")},
        {QLatin1Char('R'), QLatin1String("REPLACE")},
        {QLatin1Char('R'), QLatin1String("REPLICATION")},
        {QLatin1Char('R'), QLatin1String("REQUIRE")},
        {QLatin1Char('R'), QLatin1String("RESIGNAL")},
        {QLatin1Char('R'), QLatin1String("RESTORE")},
        {QLatin1Char('R'), QLatin1String("RESTRICT")},
        {QLatin1Char('R'), QLatin1String("RETURNS")},
        {QLatin1Char('R'), QLatin1String("REVOKE")},
        {QLatin1Char('R'), QLatin1String("RIGHT")},
        {QLatin1Char('R'), QLatin1String("ROLLBACK")},
        {QLatin1Char('R'), QLatin1String("ROUTINE")},
        {QLatin1Char('R'), QLatin1String("ROWCOUNT")},
        {QLatin1Char('G'), QLatin1String("GUIDCOL")},
        {QLatin1Char('R'), QLatin1String("RTREE")},
        {QLatin1Char('R'), QLatin1String("RULE")},
        {QLatin1Char('S'), QLatin1String("SAVEPOINT")},
        {QLatin1Char('S'), QLatin1String("SCHEMA")},
        {QLatin1Char('S'), QLatin1String("SECOND")},
        {QLatin1Char('S'), QLatin1String("SELECT")},
        {QLatin1Char('S'), QLatin1String("SERIALIZABLE")},
        {QLatin1Char('S'), QLatin1String("SESSION_USER")},
        {QLatin1Char('S'), QLatin1String("SETUSER")},
        {QLatin1Char('S'), QLatin1String("SHARE")},
        {QLatin1Char('S'), QLatin1String("SHOW")},
        {QLatin1Char('S'), QLatin1String("SHUTDOWN")},
        {QLatin1Char('S'), QLatin1String("SIMPLE")},
        {QLatin1Char('S'), QLatin1String("SMALLINT")},
        {QLatin1Char('S'), QLatin1String("SNAPSHOT")},
        {QLatin1Char('S'), QLatin1String("SOME")},
        {QLatin1Char('S'), QLatin1String("SONAME")},
        {QLatin1Char('S'), QLatin1String("SQL")},
        {QLatin1Char('S'), QLatin1String("STARTING")},
        {QLatin1Char('S'), QLatin1String("STATISTICS")},
        {QLatin1Char('S'), QLatin1String("STATUS")},
        {QLatin1Char('S'), QLatin1String("STRIPED")},
        {QLatin1Char('S'), QLatin1String("SYSTEM_USER")},
        {QLatin1Char('T'), QLatin1String("TABLES")},
        {QLatin1Char('T'), QLatin1String("TABLESPACE")},
        {QLatin1Char('T'), QLatin1String("TEMPORARY")},
        {QLatin1Char('T'), QLatin1String("TABLE")},
        {QLatin1Char('T'), QLatin1String("TERMINATED")},
        {QLatin1Char('T'), QLatin1String("TEXTSIZE")},
        {QLatin1Char('T'), QLatin1String("THEN")},
        {QLatin1Char('T'), QLatin1String("TIMESTAMP")},
        {QLatin1Char('T'), QLatin1String("TINYBLOB")},
        {QLatin1Char('I'), QLatin1String("INT")},
        {QLatin1Char('T'), QLatin1String("TEXT")},
        {QLatin1Char('T'), QLatin1String("TOP")},
        {QLatin1Char('T'), QLatin1String("TRANSACTIONS")},
        {QLatin1Char('T'), QLatin1String("TRIGGER")},
        {QLatin1Char('T'), QLatin1String("TRUNCATE")},
        {QLatin1Char('T'), QLatin1String("TSEQUAL")},
        {QLatin1Char('T'), QLatin1String("TYPES")},
        {QLatin1Char('U'), QLatin1String("UNBOUNDED")},
        {QLatin1Char('U'), QLatin1String("UNCOMMITTED")},
        {QLatin1Char('U'), QLatin1String("UNDEFINED")},
        {QLatin1Char('U'), QLatin1String("UNION")},
        {QLatin1Char('U'), QLatin1String("UNIQUE")},
        {QLatin1Char('U'), QLatin1String("UNLOCK")},
        {QLatin1Char('U'), QLatin1String("UNPIVOT")},
        {QLatin1Char('U'), QLatin1String("UNSIGNED")},
        {QLatin1Char('U'), QLatin1String("UPDATETEXT")},
        {QLatin1Char('U'), QLatin1String("USAGE")},
        {QLatin1Char('U'), QLatin1String("USE")},
        {QLatin1Char('U'), QLatin1String("USER")},
        {QLatin1Char('U'), QLatin1String("USING")},
        {QLatin1Char('V'), QLatin1String("VALUES")},
        {QLatin1Char('V'), QLatin1String("VARBINARY")},
        {QLatin1Char('C'), QLatin1String("CHAR")},
        {QLatin1Char('C'), QLatin1String("CHARACTER")},
        {QLatin1Char('Y'), QLatin1String("YING")},
        {QLatin1Char('V'), QLatin1String("VIEW")},
        {QLatin1Char('W'), QLatin1String("WAITFOR")},
        {QLatin1Char('W'), QLatin1String("WARNINGS")},
        {QLatin1Char('W'), QLatin1String("WHEN")},
        {QLatin1Char('W'), QLatin1String("WHERE")},
        {QLatin1Char('W'), QLatin1String("WHILE")},
        {QLatin1Char('W'), QLatin1String("WITH")},
        {QLatin1Char('R'), QLatin1String("ROLLUP")},
        {QLatin1Char('I'), QLatin1String("IN")},
        {QLatin1Char('W'), QLatin1String("WORK")},
        {QLatin1Char('W'), QLatin1String("WRITETEXT")},
        {QLatin1Char('Y'), QLatin1String("YEAR")}
    };

    types = {

    };

    literals = {
        {QLatin1Char('A'), QLatin1String("TRUE")},
        {QLatin1Char('F'), QLatin1String("FALSE")},
        {QLatin1Char('N'), QLatin1String("NULL")},
    };

    builtin = {
        {QLatin1Char('A'), QLatin1String("AVG")},
        {QLatin1Char('C'), QLatin1String("COUNT")},
        {QLatin1Char('F'), QLatin1String("FIRST")},
        {QLatin1Char('F'), QLatin1String("FORMAT")},
        {QLatin1Char('L'), QLatin1String("LAST")},
        {QLatin1Char('L'), QLatin1String("LCASE")},
        {QLatin1Char('L'), QLatin1String("LEN")},
        {QLatin1Char('M'), QLatin1String("MAX")},
        {QLatin1Char('M'), QLatin1String("MID")},
        {QLatin1Char('M'), QLatin1String("MIN")},
        {QLatin1Char('M'), QLatin1String("MOD")},
        {QLatin1Char('N'), QLatin1String("NOW")},
        {QLatin1Char('R'), QLatin1String("ROUND")},
        {QLatin1Char('S'), QLatin1String("SUM")},
        {QLatin1Char('U'), QLatin1String("UCASE")}
    };

    other = {

    };

}
